spring:
  jpa:
    hibernate.ddl-auto: validate
    database: MYSQL
    show-sql: true
    hibernate: 
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties: 
      org.hibernate.envers.track_entities_changed_in_revision: false
  datasource:
    url: jdbc:mysql://192.168.0.26:3306/hibernate_envers_db?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: q1w2e3r4
    
# system configuration properties
project:
      security:
          enagle-https: false