CREATE TABLE TB_PEOPLE (
	PK_PERSON BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	TX_NAME   VARCHAR(50) NOT NULL,
	DT_BIRTH  DATE,
	ID_GENRE ENUM('MALE', 'FEMALE')
	
	
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO TB_PEOPLE (TX_NAME, DT_BIRTH, ID_GENRE) VALUES ('Mauricio', '1995-06-06', 'MALE');
INSERT INTO TB_PEOPLE (TX_NAME, DT_BIRTH, ID_GENRE) VALUES ('Ana','1995-05-05', 'FEMALE');
INSERT INTO TB_PEOPLE (TX_NAME, DT_BIRTH, ID_GENRE) VALUES ('Bruna','1995-04-13', 'FEMALE');
INSERT INTO TB_PEOPLE (TX_NAME, DT_BIRTH, ID_GENRE) VALUES ('Marcela','1993-01-08', 'FEMALE');
INSERT INTO TB_PEOPLE (TX_NAME, DT_BIRTH, ID_GENRE) VALUES ('Matheus', '1994-12-09', 'MALE');
