ALTER TABLE TBH_PEOPLE 
        ADD ACTIVE CHAR(1),
	ADD DT_LAST_CHANGE DATE,
	ADD ID_USER BIGINT(20);


CREATE TABLE TBH_PEOPLE (
	ID		BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	PK_PERSON      BIGINT(20),
	TX_NAME        VARCHAR(50) NOT NULL,
	DT_BIRTH       DATE,
	ID_GENRE       ENUM('MALE', 'FEMALE'),
        IACTIVE         CHAR(1),
	DT_LAST_CHANGE DATE,
	ID_USER        BIGINT(20)	
	
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


